{% set name = "dropbox" %}
{% set version = "11.13.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dropbox/dropbox-sdk-python/archive/v{{ version }}.tar.gz
  sha256: 9d60b6e10a8047c71adf8897e9dfd619d0db6a0949462d082e90b637441380fd

build:
  number: 0
  skip: True  # [win]
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner ==5.2.0
    - python =2.7|>=3.4
    - wheel
    - setuptools
  run:
    - python =2.7|>=3.4
    - requests >=2.16.2
    - six >=1.12.0
    - stone >=2.*

test:
  requires:
    - pip
    - mock
    - pytest-mock
    - coverage
    - pytest
    - coverage
    - stone >=2.*
  imports:
    - dropbox
  commands:
    - pip check
    - pytest test/unit/test_dropbox_unit.py
  source_files:
    - test

about:
  home: http://www.dropbox.com/developers
  summary: Official Dropbox API Client
  description: The Official Dropbox API V2 SDK for Python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/dropbox/dropbox-sdk-python
  doc_url: https://dropbox-sdk-python.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - guillochon
    - BastianZim
