{% set name = "dropbox" %}
{% set version = "12.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}-sdk-python/archive/v{{ version }}.tar.gz
  sha256: 54077e15dd235524ab5ed0fcb9f8f7470039d74e51473f0dc81791db2528e361
  patches:
    # Use latest patch version for stone
    - patches/0001-Updated-stone-upper-bound.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<311]

requirements:
  host:
    - pip
    - pytest-runner <=5.2.0
    - python
    - setuptools >=77.0
  run:
    - python
    - requests >=2.16.2
    - six >=1.12.0
    - stone >=3.5.1,<4

test:
  source_files:
    - test
  imports:
    - dropbox
    - dropbox.auth
    - dropbox.base
    - dropbox.base_team
    - dropbox.common
    - dropbox.dropbox_client
    - dropbox.exceptions
    - dropbox.oauth
    - dropbox.session
  commands:
    - pip check
    - pytest test/unit/test_dropbox_unit.py
  requires:
    - python
    - pip
    - mock
    - pytest-mock
    - coverage

about:
  home: https://www.dropbox.com/developers
  summary: Official Dropbox API Client
  description: The Official Dropbox API V2 SDK for Python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/dropbox/dropbox-sdk-python
  doc_url: https://dropbox-sdk-python.readthedocs.io

extra:
  recipe-maintainers:
    - guillochon
    - BastianZim
  skip-lints:
    - invalid_url
