{% set version = "11.4.1" %}

package:
  name: dropbox
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/dropbox/dropbox-{{ version }}.tar.gz
  sha256: 7ba43384029424779a4b3ec8d5832362c5c0f37cd644be2fb87e2b30a569849e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner ==5.2.0
    - python =2.7|>=3.4
  run:
    - python =2.7|>=3.4
    - requests >=2.16.2
    - six >=1.12.0
    - stone >=2

test:
  imports:
    - dropbox

about:
  home: https://github.com/dropbox/dropbox-sdk-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Official Dropbox API Client'
  dev_url: https://github.com/dropbox/dropbox-sdk-python
  doc_url: https://dropbox-sdk-python.readthedocs.io/en/latest/

  description: |
    dropbox is a Python SDK for integrating with the Dropbox API v2.
    Compatible with Python 2.7 and 3.4+. Documentation is available on
    Read the Docs.

extra:
  recipe-maintainers:
    - guillochon
