{% set name = "dropbox" %}
{% set version = "12.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}-sdk-python/archive/v{{ version }}.tar.gz
  sha256: eec8095311fcc8b4f48f6cd3a2ee539dbf18ffc906091c80c36ac042978c5093

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - pytest-runner 5.2.0
    - python
    - wheel
    - setuptools
  run:
    - python
    - requests >=2.16.2
    - six >=1.12.0
    - stone >=2,<3.3.3

test:
  source_files:
    - test
  imports:
    - dropbox
    - dropbox.auth
    - dropbox.base
    - dropbox.base_team
    - dropbox.common
    - dropbox.dropbox_client
    - dropbox.exceptions
    - dropbox.oauth
    - dropbox.session
  commands:
    - pip check
    - pytest test/unit/test_dropbox_unit.py
  requires:
    - python
    - pip
    - mock
    - pytest-mock
    - coverage

about:
  home: https://www.dropbox.com/developers
  summary: Official Dropbox API Client
  description: The Official Dropbox API V2 SDK for Python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/dropbox/dropbox-sdk-python
  doc_url: https://dropbox-sdk-python.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - guillochon
    - BastianZim
  skip-lints:
    - invalid_url
