# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "M2TaZx2YNGx3AOABRZa/pQySFTkhfKLBh+0CNmh/FiXsqgd/s0R3fniGxACD1kVk1CUp/yWHif2FPrHUlBbRA2z+AzVAzTc9fT8y2X+hEnLTo4LChuIFmSMhK5rkuI87xj4OHhaKqv3Qn9OsgGpgrGxAILvuHI1DEPStaDEY7Zpdcd859oZBl7YggQBPcbXxHzmiQLsiJHpQ4ROrRcnLHPVq/VQunaBzW2hAAaM4Zb10Oc7DhFgen06MDDixaOgDttiTz6zSaBCOiRJp++EgSVitqZa2mCt4NcpjZNIrwEGTHsAsqZKl5BUvbvlmnz8zUgQ4/1jTgvF6PO8bgvGggi/90f4QHyi9oqlEMqHlKMwuN7k2g8n/uDHPNU9jFNZYRXcWeM3Gb3ttOUqyibXsoIDGIsw0Qv1LWw7wl3R2vTf/+j9NYHCnfqV1IvEPuIKj5/9G1Y/KRJumtpoDHbwBlb2QMbvEkfUubJSeLuAMTT8QaOMv5d8ZzdO4dQnQYy42ymvH1iV5xHmsDT+Kwt2M1Q+ol56tWLRkpFLFXmgP3ZdZnOEiJBMxDroobZz9UYloqBw5lkPkr0kEwGkSeVSf0e2F3ct230FqQZ+NuRLbcMpQZsr06R/QQEwzGqESw8oRYfdL+9xCxSDhr7qOufbyG09HsRf3x6SfMSzsr6B1sLo="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
