travis:
  secure:
    BINSTAR_TOKEN: i2ChpJ7X04K78pKcSg6+y7xwO3li3r7RCVF5TxmKA61vGHF6iZGgDXAXllPOs8SM5vOOdTk4YIPADhBf3EfDhmJE7M8/OwKrX4zxPFNX/Bb9zS5jTDEolqajn9+fvcwIzj4l7JUBT3EVoQO+STvjpZX4JbFxV5TQRT9fAqSnCKEu9D4PebEqi4cUnyhvX/vRJL8NX3BGeNp42h89rWOU4GG62JzsRuPXUk0Z8ioSPT4OCHIWbpMAZo1gOJwXRY/VnbeDRxUxZ8ks9tOE3shg9SaBuCkWVshxoH5JWe3Gci0ik20ryeMndtrFbW818llaEFG0+RYUbe91cDKyOPAureKh4IbQF+th5XKuYBQiSjtL9s8GhzPy9aUJmb5Y+pFrEV5Og7Byoyt6+vOMMm/4UvagY1P6q+N/d7Yhn9zh5V5r90KNcq7YITFSGDYXQIiYgT43CRkMnB1jupxmvfQOdrOzAOzEa7FEm4VtRdgpeHTdEDOOspxFLGOrXbqjuMCQjtbah8yK91VKKNag54hR/fFO2jp6DP0lB2EjNoeW9r6ccghxfOmg/kxLFzZs0kiIn1MqEehrmgVzr8bKBqxkpdwYQhGjxwvk2onn9/9z6yY38ZcEQg83mUDqbjhRONa1Ew8m6T0cvdXRX0Z7UTlyDSN5hkkgg1RgPNs8ie3kFbM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
