travis:
  secure:
    BINSTAR_TOKEN: M2TaZx2YNGx3AOABRZa/pQySFTkhfKLBh+0CNmh/FiXsqgd/s0R3fniGxACD1kVk1CUp/yWHif2FPrHUlBbRA2z+AzVAzTc9fT8y2X+hEnLTo4LChuIFmSMhK5rkuI87xj4OHhaKqv3Qn9OsgGpgrGxAILvuHI1DEPStaDEY7Zpdcd859oZBl7YggQBPcbXxHzmiQLsiJHpQ4ROrRcnLHPVq/VQunaBzW2hAAaM4Zb10Oc7DhFgen06MDDixaOgDttiTz6zSaBCOiRJp++EgSVitqZa2mCt4NcpjZNIrwEGTHsAsqZKl5BUvbvlmnz8zUgQ4/1jTgvF6PO8bgvGggi/90f4QHyi9oqlEMqHlKMwuN7k2g8n/uDHPNU9jFNZYRXcWeM3Gb3ttOUqyibXsoIDGIsw0Qv1LWw7wl3R2vTf/+j9NYHCnfqV1IvEPuIKj5/9G1Y/KRJumtpoDHbwBlb2QMbvEkfUubJSeLuAMTT8QaOMv5d8ZzdO4dQnQYy42ymvH1iV5xHmsDT+Kwt2M1Q+ol56tWLRkpFLFXmgP3ZdZnOEiJBMxDroobZz9UYloqBw5lkPkr0kEwGkSeVSf0e2F3ct230FqQZ+NuRLbcMpQZsr06R/QQEwzGqESw8oRYfdL+9xCxSDhr7qOufbyG09HsRf3x6SfMSzsr6B1sLo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
