travis:
  secure:
    BINSTAR_TOKEN: cgvjEO7a7GGLk1ItDWBQPdvfrQH7OwVOJZH/2WkemmqW67/6UVMq+WUJwOsAg+ZaTpD2xaS4CEnxegkwGCJQ5Cz6BdsITni7EkoBMVBQs18wAH7ISYJsCnGSLorq1mZ4pmOFreqo+iDfhdpoiWFGtwINCWrqVl++uxP0KFCG/OYoSxoUriwaX1r0TGNfpTfF81YfGcwo+k1dfVduYbx0wgrhZbZoXkiKwuEBuE/oSUwAh/U/kiltIz+a9b2Oujw2b6spWDITQqbtBGd7BguhdYdgU+U0ptUl/I8k1YJz2ay0Onz7ZSnOWwpGRStTEBNPc6fNkqtYppHoLJfE0k6+W9fUfaE2XH9UWJANGubopLFf+SU+E/Orb5F6CuW9EZzpNuTyB09m949AWZRlzTEaYVdLQ66m0+2FatX3/O2x8F/9RWOKq9wd9Lhge1be4v1yh2s9R+O23H5PR1teAAOisP8iLJ8nt3sZbombN9J6HonfluiJDL7u2fSsKJOqEiZj17j2wxKg81AO9Dblg1y8ySRYETFCXSBvtmoChnY36yTl3pyXPaD/WLgqZE4kFXEyUhrgU6IQrLyOFtXtbITtc0xk/M7eIuK/q/FpNTBUMwAFyPuJDhyi2s8qecYUtPe25ANWT0osZcccV1+G9GbAUwg5SDw63Xu3U9MIDNPe510=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
